source 'https://rubygems.org'

gem 'rails', '4.2.0.rc1'
gem 'pg'
gem 'sass-rails', '~> 4.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'spring'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'bcrypt', '~> 3.1.7'

# gem 'unicorn'
# gem 'capistrano-rails', group: :development
group :development do
  gem 'byebug'
end
group :development, :test do
  gem 'rspec-rails'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'factory_girl_rails'
  gem 'faker'
end

group :test do
  gem 'guard-rspec'
  gem 'capybara'
  gem 'launchy'
end
